CREATE TABLE appointments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id BIGINT,
    doctor_id  BIGINT,
    date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appointments PRIMARY KEY (id)
);

CREATE TABLE doctors
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    surname        VARCHAR(255),
    age            INTEGER,
    pesel          BIGINT,
    specialization VARCHAR(255),
    CONSTRAINT pk_doctors PRIMARY KEY (id)
);

CREATE TABLE patients
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    age     INTEGER,
    pesel   BIGINT,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctors (id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);