ALTER TABLE appointments
    DROP CONSTRAINT fk_appointments_on_doctor;

ALTER TABLE appointments
    DROP CONSTRAINT fk_appointments_on_patient;

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype          VARCHAR(31),
    name           VARCHAR(255),
    surname        VARCHAR(255),
    pesel          BIGINT,
    login          VARCHAR(255),
    password       VARCHAR(255),
    age            INTEGER,
    specialization VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_login UNIQUE (login);

ALTER TABLE users
    ADD CONSTRAINT uc_users_pesel UNIQUE (pesel);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES users (id);

ALTER TABLE appointments
    ADD CONSTRAINT FK_APPOINTMENTS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES users (id);

DROP TABLE doctors CASCADE;

DROP TABLE patients CASCADE;